### ISSUE TITLE
Problem with title reload and title clear 

### ISSUE THREAD

**Issue by fogracvxy** [DrkMatr1984/dsTitles#3]
Everytime i reload or title clear chat goes wild but when i type second message in chat it turns back into normal & and after reload titles are removed have to be assigned again

There is a log of this 
https://pastebin.com/QjZixGXd

**Comment by DrkMatr1984** [comment]
Still haven't had time to check this out more, but I've uploaded the source for the fix for the JSON clicking, and here is the jar for this version. As a temporary workaround, don't give players the permission to clear their title, they can just select a new title when they want to (Or create a blank title that you switch them to yourself), and only reload the plugin with a server restart or plugman until I get a chance to fix it.
[dsTitle-1.5.3.jar.zip](https://github.com/DrkMatr1984/dsTitles/files/2872417/dsTitle-1.5.3.jar.zip)

Just remove the ".zip" at the end, for some reason Github won't let you upload Jars here.

**Comment by fogracvxy** [comment]
https://github.com/FabioZumbi12/UltimateChat/wiki/(7)-UChat-API
I was thinking of implementation of this into dstitle would be great thing

**Comment by DrkMatr1984** [comment]
I recently fixed the two bugs you were having, and updated the plugin quite a bit. I will be releasing an update soon.
d0761aff3fc2849bf8b2b1e4135719c5dca91f46
